const { createFixBranchAndCommit } = require("../tools/githubOps");

async function runFixerAgent(payload) {
  const prNumber = payload?.prNumber;

  // TODO: wire LangChain + model provider with stack trace context.
  const patchProposal = {
    summary: "Placeholder fix generated by fixer agent",
    files: [],
  };

  await createFixBranchAndCommit({ prNumber, patchProposal });
  return { ok: true, prNumber, patchProposal };
}

module.exports = { runFixerAgent };
