const simpleGit = require("simple-git");
const path = require("path");
const fs = require("fs");
const { execSync } = require("child_process");
const { Octokit } = require("@octokit/rest");

async function createFixBranchAndCommit({ prNumber, patchProposal }) {
  const defaultTestRepo = path.resolve(__dirname, '../../scripts/test-repo');
  const targetRepo = process.env.TEST_REPO_PATH || defaultTestRepo;
  
  // Guard 1: Must strictly be within the test repo, not a sibling
  if (targetRepo !== defaultTestRepo && !targetRepo.startsWith(defaultTestRepo + path.sep)) {
    throw new Error(`SAFETY GUARD: Refusing to run git ops outside of test-repo. Target was: ${targetRepo}`);
  }

  const git = simpleGit(targetRepo);
  
  const isRepo = await git.checkIsRepo();
  if (!isRepo) {
    await git.init();
    await git.add('.');
    await git.commit('Initial commit for test repo');
  }

  // Branch state bug: checkout base branch first (assuming master or main)
  try {
    await git.checkout('main');
  } catch (e) {
    try {
      await git.checkout('master');
    } catch (e2) {
      // If neither exists, just stay on current branch (might be initial commit)
    }
  }

  const branch = `ai/fix-pr-${prNumber || 'unknown'}-${Date.now()}`;
  
  await git.checkoutLocalBranch(branch);
  
  const filesWritten = [];
  const filesToRevert = [];

  try {
    // Apply patch
    const filesToPatch = (patchProposal && patchProposal.filepath && patchProposal.content) 
      ? [patchProposal] 
      : (patchProposal && patchProposal.files) ? patchProposal.files : [];

    for (const file of filesToPatch) {
      const fullPath = path.resolve(targetRepo, file.filepath);
      // Path traversal guard
      if (!fullPath.startsWith(targetRepo + path.sep)) {
         throw new Error(`SAFETY GUARD: Path traversal detected: ${fullPath}`);
      }
      
      const originalContent = fs.existsSync(fullPath) ? fs.readFileSync(fullPath, 'utf8') : null;
      filesToRevert.push({ path: fullPath, content: originalContent });
      
      fs.writeFileSync(fullPath, file.content);
      filesWritten.push(fullPath);
    }

    // Verify before commit
    // Find matching test file if this is the test-repo. For simplicity, any .js in bugs/ has a .test.js
    for (const file of filesToPatch) {
      const testFile = file.filepath.replace('.js', '.test.js');
      const testFilePath = path.resolve(targetRepo, testFile);
      if (fs.existsSync(testFilePath)) {
        try {
          execSync(`node "${testFilePath}"`, { stdio: 'pipe' });
        } catch (e) {
          const errMsg = (e.stdout ? e.stdout.toString() : '') + (e.stderr ? e.stderr.toString() : '') + e.message;
          throw new Error(`Verification failed on ${testFile}:\n${errMsg}`);
        }
      }
    }
    
    // Stage and commit
    for (const file of filesToPatch) {
      await git.add(file.filepath);
    }
    await git.commit(patchProposal.summary || `chore(ai-fix): automated fix for PR #${prNumber || 'unknown'}`);

  } catch (e) {
    // Revert files and throw
    for (const revert of filesToRevert) {
      if (revert.content !== null) {
        fs.writeFileSync(revert.path, revert.content);
      } else {
        if (fs.existsSync(revert.path)) fs.unlinkSync(revert.path);
      }
    }
    // Also checkout base branch so we don't leave them on a broken branch
    try { await git.checkout('main'); } catch(err) { try { await git.checkout('master'); } catch(err2){} }
    throw e; // throw verification error up to agent
  }
  
  let pushSuccess = false;
  let prUrl = null;

  try {
    const remotes = await git.getRemotes();
    if (remotes.length > 0) {
      await git.push('origin', branch, { '--force': null }); // force push in case it already existed remotely
      pushSuccess = true;
      
      // PR Creation
      if (process.env.GITHUB_TOKEN && process.env.GITHUB_REPO_OWNER && process.env.GITHUB_REPO_NAME) {
         const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
         const prResponse = await octokit.rest.pulls.create({
           owner: process.env.GITHUB_REPO_OWNER,
           repo: process.env.GITHUB_REPO_NAME,
           title: patchProposal.summary || `Automated fix for PR #${prNumber}`,
           head: branch,
           base: 'main', // Assuming main is base, ideally configurable
           body: `Automated fix generated by AI Worker.`
         });
         prUrl = prResponse.data.html_url;
      }
    }
  } catch (err) {
    throw new Error(`Push or PR creation failed: ${err.message}`);
  }

  return { branch, pushSuccess, prUrl, patchProposal };
}

module.exports = { createFixBranchAndCommit };
